name: Build/release

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Upgrade yarn version
        run: corepack prepare yarn@3.3.0 --activate

      - name: Build and release with electron-builder
        run: |
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          yarn
          yarn dist -c.snap.publish=github
        shell: bash
